// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DaemonToTuyaConnectWIFI.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DaemonToTuyaConnectWIFI_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DaemonToTuyaConnectWIFI_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DaemonToTuyaConnectWIFI_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DaemonToTuyaConnectWIFI_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DaemonToTuyaConnectWIFI_2eproto;
namespace LSLAM {
class DistributionNetworkBegin;
struct DistributionNetworkBeginDefaultTypeInternal;
extern DistributionNetworkBeginDefaultTypeInternal _DistributionNetworkBegin_default_instance_;
}  // namespace LSLAM
PROTOBUF_NAMESPACE_OPEN
template<> ::LSLAM::DistributionNetworkBegin* Arena::CreateMaybeMessage<::LSLAM::DistributionNetworkBegin>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace LSLAM {

enum ErrorMessage : int {
  EM_UNUSED = 0,
  EM_DONOT_DISTURB = 1,
  EM_LOWER_BETTERY_SLEEP = 2,
  EM_LOWER_BETTERY_RECHARGE = 3,
  EM_ROBOT_RUNING = 4,
  ErrorMessage_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ErrorMessage_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ErrorMessage_IsValid(int value);
constexpr ErrorMessage ErrorMessage_MIN = EM_UNUSED;
constexpr ErrorMessage ErrorMessage_MAX = EM_ROBOT_RUNING;
constexpr int ErrorMessage_ARRAYSIZE = ErrorMessage_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorMessage_descriptor();
template<typename T>
inline const std::string& ErrorMessage_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorMessage>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorMessage_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorMessage_descriptor(), enum_t_value);
}
inline bool ErrorMessage_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorMessage* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorMessage>(
    ErrorMessage_descriptor(), name, value);
}
// ===================================================================

class DistributionNetworkBegin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LSLAM.DistributionNetworkBegin) */ {
 public:
  inline DistributionNetworkBegin() : DistributionNetworkBegin(nullptr) {}
  ~DistributionNetworkBegin() override;
  explicit PROTOBUF_CONSTEXPR DistributionNetworkBegin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DistributionNetworkBegin(const DistributionNetworkBegin& from);
  DistributionNetworkBegin(DistributionNetworkBegin&& from) noexcept
    : DistributionNetworkBegin() {
    *this = ::std::move(from);
  }

  inline DistributionNetworkBegin& operator=(const DistributionNetworkBegin& from) {
    CopyFrom(from);
    return *this;
  }
  inline DistributionNetworkBegin& operator=(DistributionNetworkBegin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DistributionNetworkBegin& default_instance() {
    return *internal_default_instance();
  }
  static inline const DistributionNetworkBegin* internal_default_instance() {
    return reinterpret_cast<const DistributionNetworkBegin*>(
               &_DistributionNetworkBegin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DistributionNetworkBegin& a, DistributionNetworkBegin& b) {
    a.Swap(&b);
  }
  inline void Swap(DistributionNetworkBegin* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DistributionNetworkBegin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DistributionNetworkBegin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DistributionNetworkBegin>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DistributionNetworkBegin& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DistributionNetworkBegin& from) {
    DistributionNetworkBegin::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DistributionNetworkBegin* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LSLAM.DistributionNetworkBegin";
  }
  protected:
  explicit DistributionNetworkBegin(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDistributionNetworkBeginFieldNumber = 1,
    kBatteryLevelFieldNumber = 2,
    kUpperStrataFirmwareUpdateFieldNumber = 3,
    kBottomFirmwareUpdateFieldNumber = 4,
    kChargingFieldNumber = 5,
    kChargingCompletedFieldNumber = 6,
    kDaemonToTuyaErrorMessageFieldNumber = 7,
  };
  // int32 distribution_network_begin = 1;
  void clear_distribution_network_begin();
  int32_t distribution_network_begin() const;
  void set_distribution_network_begin(int32_t value);
  private:
  int32_t _internal_distribution_network_begin() const;
  void _internal_set_distribution_network_begin(int32_t value);
  public:

  // int32 battery_level = 2;
  void clear_battery_level();
  int32_t battery_level() const;
  void set_battery_level(int32_t value);
  private:
  int32_t _internal_battery_level() const;
  void _internal_set_battery_level(int32_t value);
  public:

  // int32 upper_strata_firmware_update = 3;
  void clear_upper_strata_firmware_update();
  int32_t upper_strata_firmware_update() const;
  void set_upper_strata_firmware_update(int32_t value);
  private:
  int32_t _internal_upper_strata_firmware_update() const;
  void _internal_set_upper_strata_firmware_update(int32_t value);
  public:

  // int32 bottom_firmware_update = 4;
  void clear_bottom_firmware_update();
  int32_t bottom_firmware_update() const;
  void set_bottom_firmware_update(int32_t value);
  private:
  int32_t _internal_bottom_firmware_update() const;
  void _internal_set_bottom_firmware_update(int32_t value);
  public:

  // int32 charging = 5;
  void clear_charging();
  int32_t charging() const;
  void set_charging(int32_t value);
  private:
  int32_t _internal_charging() const;
  void _internal_set_charging(int32_t value);
  public:

  // int32 charging_completed = 6;
  void clear_charging_completed();
  int32_t charging_completed() const;
  void set_charging_completed(int32_t value);
  private:
  int32_t _internal_charging_completed() const;
  void _internal_set_charging_completed(int32_t value);
  public:

  // .LSLAM.ErrorMessage daemon_to_tuya_error_message = 7;
  void clear_daemon_to_tuya_error_message();
  ::LSLAM::ErrorMessage daemon_to_tuya_error_message() const;
  void set_daemon_to_tuya_error_message(::LSLAM::ErrorMessage value);
  private:
  ::LSLAM::ErrorMessage _internal_daemon_to_tuya_error_message() const;
  void _internal_set_daemon_to_tuya_error_message(::LSLAM::ErrorMessage value);
  public:

  // @@protoc_insertion_point(class_scope:LSLAM.DistributionNetworkBegin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t distribution_network_begin_;
    int32_t battery_level_;
    int32_t upper_strata_firmware_update_;
    int32_t bottom_firmware_update_;
    int32_t charging_;
    int32_t charging_completed_;
    int daemon_to_tuya_error_message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DaemonToTuyaConnectWIFI_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DistributionNetworkBegin

// int32 distribution_network_begin = 1;
inline void DistributionNetworkBegin::clear_distribution_network_begin() {
  _impl_.distribution_network_begin_ = 0;
}
inline int32_t DistributionNetworkBegin::_internal_distribution_network_begin() const {
  return _impl_.distribution_network_begin_;
}
inline int32_t DistributionNetworkBegin::distribution_network_begin() const {
  // @@protoc_insertion_point(field_get:LSLAM.DistributionNetworkBegin.distribution_network_begin)
  return _internal_distribution_network_begin();
}
inline void DistributionNetworkBegin::_internal_set_distribution_network_begin(int32_t value) {
  
  _impl_.distribution_network_begin_ = value;
}
inline void DistributionNetworkBegin::set_distribution_network_begin(int32_t value) {
  _internal_set_distribution_network_begin(value);
  // @@protoc_insertion_point(field_set:LSLAM.DistributionNetworkBegin.distribution_network_begin)
}

// int32 battery_level = 2;
inline void DistributionNetworkBegin::clear_battery_level() {
  _impl_.battery_level_ = 0;
}
inline int32_t DistributionNetworkBegin::_internal_battery_level() const {
  return _impl_.battery_level_;
}
inline int32_t DistributionNetworkBegin::battery_level() const {
  // @@protoc_insertion_point(field_get:LSLAM.DistributionNetworkBegin.battery_level)
  return _internal_battery_level();
}
inline void DistributionNetworkBegin::_internal_set_battery_level(int32_t value) {
  
  _impl_.battery_level_ = value;
}
inline void DistributionNetworkBegin::set_battery_level(int32_t value) {
  _internal_set_battery_level(value);
  // @@protoc_insertion_point(field_set:LSLAM.DistributionNetworkBegin.battery_level)
}

// int32 upper_strata_firmware_update = 3;
inline void DistributionNetworkBegin::clear_upper_strata_firmware_update() {
  _impl_.upper_strata_firmware_update_ = 0;
}
inline int32_t DistributionNetworkBegin::_internal_upper_strata_firmware_update() const {
  return _impl_.upper_strata_firmware_update_;
}
inline int32_t DistributionNetworkBegin::upper_strata_firmware_update() const {
  // @@protoc_insertion_point(field_get:LSLAM.DistributionNetworkBegin.upper_strata_firmware_update)
  return _internal_upper_strata_firmware_update();
}
inline void DistributionNetworkBegin::_internal_set_upper_strata_firmware_update(int32_t value) {
  
  _impl_.upper_strata_firmware_update_ = value;
}
inline void DistributionNetworkBegin::set_upper_strata_firmware_update(int32_t value) {
  _internal_set_upper_strata_firmware_update(value);
  // @@protoc_insertion_point(field_set:LSLAM.DistributionNetworkBegin.upper_strata_firmware_update)
}

// int32 bottom_firmware_update = 4;
inline void DistributionNetworkBegin::clear_bottom_firmware_update() {
  _impl_.bottom_firmware_update_ = 0;
}
inline int32_t DistributionNetworkBegin::_internal_bottom_firmware_update() const {
  return _impl_.bottom_firmware_update_;
}
inline int32_t DistributionNetworkBegin::bottom_firmware_update() const {
  // @@protoc_insertion_point(field_get:LSLAM.DistributionNetworkBegin.bottom_firmware_update)
  return _internal_bottom_firmware_update();
}
inline void DistributionNetworkBegin::_internal_set_bottom_firmware_update(int32_t value) {
  
  _impl_.bottom_firmware_update_ = value;
}
inline void DistributionNetworkBegin::set_bottom_firmware_update(int32_t value) {
  _internal_set_bottom_firmware_update(value);
  // @@protoc_insertion_point(field_set:LSLAM.DistributionNetworkBegin.bottom_firmware_update)
}

// int32 charging = 5;
inline void DistributionNetworkBegin::clear_charging() {
  _impl_.charging_ = 0;
}
inline int32_t DistributionNetworkBegin::_internal_charging() const {
  return _impl_.charging_;
}
inline int32_t DistributionNetworkBegin::charging() const {
  // @@protoc_insertion_point(field_get:LSLAM.DistributionNetworkBegin.charging)
  return _internal_charging();
}
inline void DistributionNetworkBegin::_internal_set_charging(int32_t value) {
  
  _impl_.charging_ = value;
}
inline void DistributionNetworkBegin::set_charging(int32_t value) {
  _internal_set_charging(value);
  // @@protoc_insertion_point(field_set:LSLAM.DistributionNetworkBegin.charging)
}

// int32 charging_completed = 6;
inline void DistributionNetworkBegin::clear_charging_completed() {
  _impl_.charging_completed_ = 0;
}
inline int32_t DistributionNetworkBegin::_internal_charging_completed() const {
  return _impl_.charging_completed_;
}
inline int32_t DistributionNetworkBegin::charging_completed() const {
  // @@protoc_insertion_point(field_get:LSLAM.DistributionNetworkBegin.charging_completed)
  return _internal_charging_completed();
}
inline void DistributionNetworkBegin::_internal_set_charging_completed(int32_t value) {
  
  _impl_.charging_completed_ = value;
}
inline void DistributionNetworkBegin::set_charging_completed(int32_t value) {
  _internal_set_charging_completed(value);
  // @@protoc_insertion_point(field_set:LSLAM.DistributionNetworkBegin.charging_completed)
}

// .LSLAM.ErrorMessage daemon_to_tuya_error_message = 7;
inline void DistributionNetworkBegin::clear_daemon_to_tuya_error_message() {
  _impl_.daemon_to_tuya_error_message_ = 0;
}
inline ::LSLAM::ErrorMessage DistributionNetworkBegin::_internal_daemon_to_tuya_error_message() const {
  return static_cast< ::LSLAM::ErrorMessage >(_impl_.daemon_to_tuya_error_message_);
}
inline ::LSLAM::ErrorMessage DistributionNetworkBegin::daemon_to_tuya_error_message() const {
  // @@protoc_insertion_point(field_get:LSLAM.DistributionNetworkBegin.daemon_to_tuya_error_message)
  return _internal_daemon_to_tuya_error_message();
}
inline void DistributionNetworkBegin::_internal_set_daemon_to_tuya_error_message(::LSLAM::ErrorMessage value) {
  
  _impl_.daemon_to_tuya_error_message_ = value;
}
inline void DistributionNetworkBegin::set_daemon_to_tuya_error_message(::LSLAM::ErrorMessage value) {
  _internal_set_daemon_to_tuya_error_message(value);
  // @@protoc_insertion_point(field_set:LSLAM.DistributionNetworkBegin.daemon_to_tuya_error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace LSLAM

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::LSLAM::ErrorMessage> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::LSLAM::ErrorMessage>() {
  return ::LSLAM::ErrorMessage_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DaemonToTuyaConnectWIFI_2eproto
