// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Laserscan.proto

#include "Laserscan.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace LSLAM {
PROTOBUF_CONSTEXPR Laserscan::Laserscan(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ranges_)*/{}
  , /*decltype(_impl_.intensities_)*/{}
  , /*decltype(_impl_.header_)*/nullptr
  , /*decltype(_impl_.angle_min_)*/0
  , /*decltype(_impl_.angle_max_)*/0
  , /*decltype(_impl_.angle_increment_)*/0
  , /*decltype(_impl_.time_increment_)*/0
  , /*decltype(_impl_.scan_time_)*/0
  , /*decltype(_impl_.range_min_)*/0
  , /*decltype(_impl_.range_max_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LaserscanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LaserscanDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LaserscanDefaultTypeInternal() {}
  union {
    Laserscan _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LaserscanDefaultTypeInternal _Laserscan_default_instance_;
}  // namespace LSLAM
static ::_pb::Metadata file_level_metadata_Laserscan_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Laserscan_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Laserscan_2eproto = nullptr;

const uint32_t TableStruct_Laserscan_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _split_
  ~0u,  // no sizeof(Split)
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.angle_min_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.angle_max_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.angle_increment_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.time_increment_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.scan_time_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.range_min_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.range_max_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.ranges_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::Laserscan, _impl_.intensities_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::LSLAM::Laserscan)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::LSLAM::_Laserscan_default_instance_._instance,
};

const char descriptor_table_protodef_Laserscan_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017Laserscan.proto\022\005LSLAM\032\014Header.proto\"\337"
  "\001\n\tLaserscan\022\035\n\006header\030\001 \001(\0132\r.LSLAM.Hea"
  "der\022\021\n\tangle_min\030\002 \001(\001\022\021\n\tangle_max\030\003 \001("
  "\001\022\027\n\017angle_increment\030\004 \001(\001\022\026\n\016time_incre"
  "ment\030\005 \001(\001\022\021\n\tscan_time\030\006 \001(\001\022\021\n\trange_m"
  "in\030\007 \001(\001\022\021\n\trange_max\030\010 \001(\001\022\016\n\006ranges\030\t "
  "\003(\001\022\023\n\013intensities\030\n \003(\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Laserscan_2eproto_deps[1] = {
  &::descriptor_table_Header_2eproto,
};
static ::_pbi::once_flag descriptor_table_Laserscan_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Laserscan_2eproto = {
    false, false, 272, descriptor_table_protodef_Laserscan_2eproto,
    "Laserscan.proto",
    &descriptor_table_Laserscan_2eproto_once, descriptor_table_Laserscan_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_Laserscan_2eproto::offsets,
    file_level_metadata_Laserscan_2eproto, file_level_enum_descriptors_Laserscan_2eproto,
    file_level_service_descriptors_Laserscan_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Laserscan_2eproto_getter() {
  return &descriptor_table_Laserscan_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Laserscan_2eproto(&descriptor_table_Laserscan_2eproto);
namespace LSLAM {

// ===================================================================

class Laserscan::_Internal {
 public:
  static const ::LSLAM::Header& header(const Laserscan* msg);
};

const ::LSLAM::Header&
Laserscan::_Internal::header(const Laserscan* msg) {
  return *msg->_impl_.header_;
}
void Laserscan::clear_header() {
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
}
Laserscan::Laserscan(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:LSLAM.Laserscan)
}
Laserscan::Laserscan(const Laserscan& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Laserscan* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ranges_){from._impl_.ranges_}
    , decltype(_impl_.intensities_){from._impl_.intensities_}
    , decltype(_impl_.header_){nullptr}
    , decltype(_impl_.angle_min_){}
    , decltype(_impl_.angle_max_){}
    , decltype(_impl_.angle_increment_){}
    , decltype(_impl_.time_increment_){}
    , decltype(_impl_.scan_time_){}
    , decltype(_impl_.range_min_){}
    , decltype(_impl_.range_max_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    _this->_impl_.header_ = new ::LSLAM::Header(*from._impl_.header_);
  }
  ::memcpy(&_impl_.angle_min_, &from._impl_.angle_min_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.range_max_) -
    reinterpret_cast<char*>(&_impl_.angle_min_)) + sizeof(_impl_.range_max_));
  // @@protoc_insertion_point(copy_constructor:LSLAM.Laserscan)
}

inline void Laserscan::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ranges_){arena}
    , decltype(_impl_.intensities_){arena}
    , decltype(_impl_.header_){nullptr}
    , decltype(_impl_.angle_min_){0}
    , decltype(_impl_.angle_max_){0}
    , decltype(_impl_.angle_increment_){0}
    , decltype(_impl_.time_increment_){0}
    , decltype(_impl_.scan_time_){0}
    , decltype(_impl_.range_min_){0}
    , decltype(_impl_.range_max_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Laserscan::~Laserscan() {
  // @@protoc_insertion_point(destructor:LSLAM.Laserscan)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Laserscan::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ranges_.~RepeatedField();
  _impl_.intensities_.~RepeatedField();
  if (this != internal_default_instance()) delete _impl_.header_;
}

void Laserscan::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Laserscan::Clear() {
// @@protoc_insertion_point(message_clear_start:LSLAM.Laserscan)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ranges_.Clear();
  _impl_.intensities_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
  ::memset(&_impl_.angle_min_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.range_max_) -
      reinterpret_cast<char*>(&_impl_.angle_min_)) + sizeof(_impl_.range_max_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Laserscan::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .LSLAM.Header header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double angle_min = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.angle_min_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double angle_max = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.angle_max_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double angle_increment = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.angle_increment_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double time_increment = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.time_increment_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double scan_time = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.scan_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double range_min = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.range_min_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double range_max = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 65)) {
          _impl_.range_max_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double ranges = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_ranges(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 73) {
          _internal_add_ranges(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double intensities = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_intensities(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 81) {
          _internal_add_intensities(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Laserscan::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LSLAM.Laserscan)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .LSLAM.Header header = 1;
  if (this->_internal_has_header()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::header(this),
        _Internal::header(this).GetCachedSize(), target, stream);
  }

  // double angle_min = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_min = this->_internal_angle_min();
  uint64_t raw_angle_min;
  memcpy(&raw_angle_min, &tmp_angle_min, sizeof(tmp_angle_min));
  if (raw_angle_min != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_angle_min(), target);
  }

  // double angle_max = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_max = this->_internal_angle_max();
  uint64_t raw_angle_max;
  memcpy(&raw_angle_max, &tmp_angle_max, sizeof(tmp_angle_max));
  if (raw_angle_max != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_angle_max(), target);
  }

  // double angle_increment = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_increment = this->_internal_angle_increment();
  uint64_t raw_angle_increment;
  memcpy(&raw_angle_increment, &tmp_angle_increment, sizeof(tmp_angle_increment));
  if (raw_angle_increment != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_angle_increment(), target);
  }

  // double time_increment = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time_increment = this->_internal_time_increment();
  uint64_t raw_time_increment;
  memcpy(&raw_time_increment, &tmp_time_increment, sizeof(tmp_time_increment));
  if (raw_time_increment != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_time_increment(), target);
  }

  // double scan_time = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scan_time = this->_internal_scan_time();
  uint64_t raw_scan_time;
  memcpy(&raw_scan_time, &tmp_scan_time, sizeof(tmp_scan_time));
  if (raw_scan_time != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_scan_time(), target);
  }

  // double range_min = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_range_min = this->_internal_range_min();
  uint64_t raw_range_min;
  memcpy(&raw_range_min, &tmp_range_min, sizeof(tmp_range_min));
  if (raw_range_min != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_range_min(), target);
  }

  // double range_max = 8;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_range_max = this->_internal_range_max();
  uint64_t raw_range_max;
  memcpy(&raw_range_max, &tmp_range_max, sizeof(tmp_range_max));
  if (raw_range_max != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(8, this->_internal_range_max(), target);
  }

  // repeated double ranges = 9;
  if (this->_internal_ranges_size() > 0) {
    target = stream->WriteFixedPacked(9, _internal_ranges(), target);
  }

  // repeated double intensities = 10;
  if (this->_internal_intensities_size() > 0) {
    target = stream->WriteFixedPacked(10, _internal_intensities(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LSLAM.Laserscan)
  return target;
}

size_t Laserscan::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LSLAM.Laserscan)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double ranges = 9;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_ranges_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated double intensities = 10;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_intensities_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // .LSLAM.Header header = 1;
  if (this->_internal_has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.header_);
  }

  // double angle_min = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_min = this->_internal_angle_min();
  uint64_t raw_angle_min;
  memcpy(&raw_angle_min, &tmp_angle_min, sizeof(tmp_angle_min));
  if (raw_angle_min != 0) {
    total_size += 1 + 8;
  }

  // double angle_max = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_max = this->_internal_angle_max();
  uint64_t raw_angle_max;
  memcpy(&raw_angle_max, &tmp_angle_max, sizeof(tmp_angle_max));
  if (raw_angle_max != 0) {
    total_size += 1 + 8;
  }

  // double angle_increment = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_increment = this->_internal_angle_increment();
  uint64_t raw_angle_increment;
  memcpy(&raw_angle_increment, &tmp_angle_increment, sizeof(tmp_angle_increment));
  if (raw_angle_increment != 0) {
    total_size += 1 + 8;
  }

  // double time_increment = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time_increment = this->_internal_time_increment();
  uint64_t raw_time_increment;
  memcpy(&raw_time_increment, &tmp_time_increment, sizeof(tmp_time_increment));
  if (raw_time_increment != 0) {
    total_size += 1 + 8;
  }

  // double scan_time = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scan_time = this->_internal_scan_time();
  uint64_t raw_scan_time;
  memcpy(&raw_scan_time, &tmp_scan_time, sizeof(tmp_scan_time));
  if (raw_scan_time != 0) {
    total_size += 1 + 8;
  }

  // double range_min = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_range_min = this->_internal_range_min();
  uint64_t raw_range_min;
  memcpy(&raw_range_min, &tmp_range_min, sizeof(tmp_range_min));
  if (raw_range_min != 0) {
    total_size += 1 + 8;
  }

  // double range_max = 8;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_range_max = this->_internal_range_max();
  uint64_t raw_range_max;
  memcpy(&raw_range_max, &tmp_range_max, sizeof(tmp_range_max));
  if (raw_range_max != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Laserscan::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Laserscan::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Laserscan::GetClassData() const { return &_class_data_; }


void Laserscan::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Laserscan*>(&to_msg);
  auto& from = static_cast<const Laserscan&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LSLAM.Laserscan)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.ranges_.MergeFrom(from._impl_.ranges_);
  _this->_impl_.intensities_.MergeFrom(from._impl_.intensities_);
  if (from._internal_has_header()) {
    _this->_internal_mutable_header()->::LSLAM::Header::MergeFrom(
        from._internal_header());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_min = from._internal_angle_min();
  uint64_t raw_angle_min;
  memcpy(&raw_angle_min, &tmp_angle_min, sizeof(tmp_angle_min));
  if (raw_angle_min != 0) {
    _this->_internal_set_angle_min(from._internal_angle_min());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_max = from._internal_angle_max();
  uint64_t raw_angle_max;
  memcpy(&raw_angle_max, &tmp_angle_max, sizeof(tmp_angle_max));
  if (raw_angle_max != 0) {
    _this->_internal_set_angle_max(from._internal_angle_max());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle_increment = from._internal_angle_increment();
  uint64_t raw_angle_increment;
  memcpy(&raw_angle_increment, &tmp_angle_increment, sizeof(tmp_angle_increment));
  if (raw_angle_increment != 0) {
    _this->_internal_set_angle_increment(from._internal_angle_increment());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time_increment = from._internal_time_increment();
  uint64_t raw_time_increment;
  memcpy(&raw_time_increment, &tmp_time_increment, sizeof(tmp_time_increment));
  if (raw_time_increment != 0) {
    _this->_internal_set_time_increment(from._internal_time_increment());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scan_time = from._internal_scan_time();
  uint64_t raw_scan_time;
  memcpy(&raw_scan_time, &tmp_scan_time, sizeof(tmp_scan_time));
  if (raw_scan_time != 0) {
    _this->_internal_set_scan_time(from._internal_scan_time());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_range_min = from._internal_range_min();
  uint64_t raw_range_min;
  memcpy(&raw_range_min, &tmp_range_min, sizeof(tmp_range_min));
  if (raw_range_min != 0) {
    _this->_internal_set_range_min(from._internal_range_min());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_range_max = from._internal_range_max();
  uint64_t raw_range_max;
  memcpy(&raw_range_max, &tmp_range_max, sizeof(tmp_range_max));
  if (raw_range_max != 0) {
    _this->_internal_set_range_max(from._internal_range_max());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Laserscan::CopyFrom(const Laserscan& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LSLAM.Laserscan)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Laserscan::IsInitialized() const {
  return true;
}

void Laserscan::InternalSwap(Laserscan* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ranges_.InternalSwap(&other->_impl_.ranges_);
  _impl_.intensities_.InternalSwap(&other->_impl_.intensities_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Laserscan, _impl_.range_max_)
      + sizeof(Laserscan::_impl_.range_max_)
      - PROTOBUF_FIELD_OFFSET(Laserscan, _impl_.header_)>(
          reinterpret_cast<char*>(&_impl_.header_),
          reinterpret_cast<char*>(&other->_impl_.header_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Laserscan::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Laserscan_2eproto_getter, &descriptor_table_Laserscan_2eproto_once,
      file_level_metadata_Laserscan_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace LSLAM
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::LSLAM::Laserscan*
Arena::CreateMaybeMessage< ::LSLAM::Laserscan >(Arena* arena) {
  return Arena::CreateMessageInternal< ::LSLAM::Laserscan >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
