// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendLineLaserDataToRVIZ.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SendLineLaserDataToRVIZ_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SendLineLaserDataToRVIZ_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SendLineLaserDataToRVIZ_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SendLineLaserDataToRVIZ_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SendLineLaserDataToRVIZ_2eproto;
namespace LSLAM {
class LineLaserData;
struct LineLaserDataDefaultTypeInternal;
extern LineLaserDataDefaultTypeInternal _LineLaserData_default_instance_;
class LineLaserDataToRVIZ;
struct LineLaserDataToRVIZDefaultTypeInternal;
extern LineLaserDataToRVIZDefaultTypeInternal _LineLaserDataToRVIZ_default_instance_;
}  // namespace LSLAM
PROTOBUF_NAMESPACE_OPEN
template<> ::LSLAM::LineLaserData* Arena::CreateMaybeMessage<::LSLAM::LineLaserData>(Arena*);
template<> ::LSLAM::LineLaserDataToRVIZ* Arena::CreateMaybeMessage<::LSLAM::LineLaserDataToRVIZ>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace LSLAM {

// ===================================================================

class LineLaserData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LSLAM.LineLaserData) */ {
 public:
  inline LineLaserData() : LineLaserData(nullptr) {}
  ~LineLaserData() override;
  explicit PROTOBUF_CONSTEXPR LineLaserData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LineLaserData(const LineLaserData& from);
  LineLaserData(LineLaserData&& from) noexcept
    : LineLaserData() {
    *this = ::std::move(from);
  }

  inline LineLaserData& operator=(const LineLaserData& from) {
    CopyFrom(from);
    return *this;
  }
  inline LineLaserData& operator=(LineLaserData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LineLaserData& default_instance() {
    return *internal_default_instance();
  }
  static inline const LineLaserData* internal_default_instance() {
    return reinterpret_cast<const LineLaserData*>(
               &_LineLaserData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LineLaserData& a, LineLaserData& b) {
    a.Swap(&b);
  }
  inline void Swap(LineLaserData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LineLaserData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LineLaserData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LineLaserData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LineLaserData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LineLaserData& from) {
    LineLaserData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LineLaserData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LSLAM.LineLaserData";
  }
  protected:
  explicit LineLaserData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kIntensityFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double intensity = 3;
  void clear_intensity();
  double intensity() const;
  void set_intensity(double value);
  private:
  double _internal_intensity() const;
  void _internal_set_intensity(double value);
  public:

  // @@protoc_insertion_point(class_scope:LSLAM.LineLaserData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    double intensity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SendLineLaserDataToRVIZ_2eproto;
};
// -------------------------------------------------------------------

class LineLaserDataToRVIZ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LSLAM.LineLaserDataToRVIZ) */ {
 public:
  inline LineLaserDataToRVIZ() : LineLaserDataToRVIZ(nullptr) {}
  ~LineLaserDataToRVIZ() override;
  explicit PROTOBUF_CONSTEXPR LineLaserDataToRVIZ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LineLaserDataToRVIZ(const LineLaserDataToRVIZ& from);
  LineLaserDataToRVIZ(LineLaserDataToRVIZ&& from) noexcept
    : LineLaserDataToRVIZ() {
    *this = ::std::move(from);
  }

  inline LineLaserDataToRVIZ& operator=(const LineLaserDataToRVIZ& from) {
    CopyFrom(from);
    return *this;
  }
  inline LineLaserDataToRVIZ& operator=(LineLaserDataToRVIZ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LineLaserDataToRVIZ& default_instance() {
    return *internal_default_instance();
  }
  static inline const LineLaserDataToRVIZ* internal_default_instance() {
    return reinterpret_cast<const LineLaserDataToRVIZ*>(
               &_LineLaserDataToRVIZ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LineLaserDataToRVIZ& a, LineLaserDataToRVIZ& b) {
    a.Swap(&b);
  }
  inline void Swap(LineLaserDataToRVIZ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LineLaserDataToRVIZ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LineLaserDataToRVIZ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LineLaserDataToRVIZ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LineLaserDataToRVIZ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LineLaserDataToRVIZ& from) {
    LineLaserDataToRVIZ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LineLaserDataToRVIZ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LSLAM.LineLaserDataToRVIZ";
  }
  protected:
  explicit LineLaserDataToRVIZ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLineLaserDataFieldNumber = 1,
  };
  // repeated .LSLAM.LineLaserData line_laser_data = 1;
  int line_laser_data_size() const;
  private:
  int _internal_line_laser_data_size() const;
  public:
  void clear_line_laser_data();
  ::LSLAM::LineLaserData* mutable_line_laser_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LSLAM::LineLaserData >*
      mutable_line_laser_data();
  private:
  const ::LSLAM::LineLaserData& _internal_line_laser_data(int index) const;
  ::LSLAM::LineLaserData* _internal_add_line_laser_data();
  public:
  const ::LSLAM::LineLaserData& line_laser_data(int index) const;
  ::LSLAM::LineLaserData* add_line_laser_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LSLAM::LineLaserData >&
      line_laser_data() const;

  // @@protoc_insertion_point(class_scope:LSLAM.LineLaserDataToRVIZ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LSLAM::LineLaserData > line_laser_data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SendLineLaserDataToRVIZ_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LineLaserData

// double x = 1;
inline void LineLaserData::clear_x() {
  _impl_.x_ = 0;
}
inline double LineLaserData::_internal_x() const {
  return _impl_.x_;
}
inline double LineLaserData::x() const {
  // @@protoc_insertion_point(field_get:LSLAM.LineLaserData.x)
  return _internal_x();
}
inline void LineLaserData::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void LineLaserData::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:LSLAM.LineLaserData.x)
}

// double y = 2;
inline void LineLaserData::clear_y() {
  _impl_.y_ = 0;
}
inline double LineLaserData::_internal_y() const {
  return _impl_.y_;
}
inline double LineLaserData::y() const {
  // @@protoc_insertion_point(field_get:LSLAM.LineLaserData.y)
  return _internal_y();
}
inline void LineLaserData::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void LineLaserData::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:LSLAM.LineLaserData.y)
}

// double intensity = 3;
inline void LineLaserData::clear_intensity() {
  _impl_.intensity_ = 0;
}
inline double LineLaserData::_internal_intensity() const {
  return _impl_.intensity_;
}
inline double LineLaserData::intensity() const {
  // @@protoc_insertion_point(field_get:LSLAM.LineLaserData.intensity)
  return _internal_intensity();
}
inline void LineLaserData::_internal_set_intensity(double value) {
  
  _impl_.intensity_ = value;
}
inline void LineLaserData::set_intensity(double value) {
  _internal_set_intensity(value);
  // @@protoc_insertion_point(field_set:LSLAM.LineLaserData.intensity)
}

// -------------------------------------------------------------------

// LineLaserDataToRVIZ

// repeated .LSLAM.LineLaserData line_laser_data = 1;
inline int LineLaserDataToRVIZ::_internal_line_laser_data_size() const {
  return _impl_.line_laser_data_.size();
}
inline int LineLaserDataToRVIZ::line_laser_data_size() const {
  return _internal_line_laser_data_size();
}
inline void LineLaserDataToRVIZ::clear_line_laser_data() {
  _impl_.line_laser_data_.Clear();
}
inline ::LSLAM::LineLaserData* LineLaserDataToRVIZ::mutable_line_laser_data(int index) {
  // @@protoc_insertion_point(field_mutable:LSLAM.LineLaserDataToRVIZ.line_laser_data)
  return _impl_.line_laser_data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LSLAM::LineLaserData >*
LineLaserDataToRVIZ::mutable_line_laser_data() {
  // @@protoc_insertion_point(field_mutable_list:LSLAM.LineLaserDataToRVIZ.line_laser_data)
  return &_impl_.line_laser_data_;
}
inline const ::LSLAM::LineLaserData& LineLaserDataToRVIZ::_internal_line_laser_data(int index) const {
  return _impl_.line_laser_data_.Get(index);
}
inline const ::LSLAM::LineLaserData& LineLaserDataToRVIZ::line_laser_data(int index) const {
  // @@protoc_insertion_point(field_get:LSLAM.LineLaserDataToRVIZ.line_laser_data)
  return _internal_line_laser_data(index);
}
inline ::LSLAM::LineLaserData* LineLaserDataToRVIZ::_internal_add_line_laser_data() {
  return _impl_.line_laser_data_.Add();
}
inline ::LSLAM::LineLaserData* LineLaserDataToRVIZ::add_line_laser_data() {
  ::LSLAM::LineLaserData* _add = _internal_add_line_laser_data();
  // @@protoc_insertion_point(field_add:LSLAM.LineLaserDataToRVIZ.line_laser_data)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LSLAM::LineLaserData >&
LineLaserDataToRVIZ::line_laser_data() const {
  // @@protoc_insertion_point(field_list:LSLAM.LineLaserDataToRVIZ.line_laser_data)
  return _impl_.line_laser_data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace LSLAM

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SendLineLaserDataToRVIZ_2eproto
