// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TwistWithCovariance.proto

#include "TwistWithCovariance.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace LSLAM {
PROTOBUF_CONSTEXPR TwistWithCovariance::TwistWithCovariance(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.covariance_)*/{}
  , /*decltype(_impl_.twist_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TwistWithCovarianceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TwistWithCovarianceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TwistWithCovarianceDefaultTypeInternal() {}
  union {
    TwistWithCovariance _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TwistWithCovarianceDefaultTypeInternal _TwistWithCovariance_default_instance_;
}  // namespace LSLAM
static ::_pb::Metadata file_level_metadata_TwistWithCovariance_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_TwistWithCovariance_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_TwistWithCovariance_2eproto = nullptr;

const uint32_t TableStruct_TwistWithCovariance_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::LSLAM::TwistWithCovariance, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _split_
  ~0u,  // no sizeof(Split)
  PROTOBUF_FIELD_OFFSET(::LSLAM::TwistWithCovariance, _impl_.twist_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::TwistWithCovariance, _impl_.covariance_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::LSLAM::TwistWithCovariance)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::LSLAM::_TwistWithCovariance_default_instance_._instance,
};

const char descriptor_table_protodef_TwistWithCovariance_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031TwistWithCovariance.proto\022\005LSLAM\032\013Twis"
  "t.proto\"F\n\023TwistWithCovariance\022\033\n\005twist\030"
  "\001 \001(\0132\014.LSLAM.Twist\022\022\n\ncovariance\030\002 \003(\001b"
  "\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_TwistWithCovariance_2eproto_deps[1] = {
  &::descriptor_table_Twist_2eproto,
};
static ::_pbi::once_flag descriptor_table_TwistWithCovariance_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_TwistWithCovariance_2eproto = {
    false, false, 127, descriptor_table_protodef_TwistWithCovariance_2eproto,
    "TwistWithCovariance.proto",
    &descriptor_table_TwistWithCovariance_2eproto_once, descriptor_table_TwistWithCovariance_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_TwistWithCovariance_2eproto::offsets,
    file_level_metadata_TwistWithCovariance_2eproto, file_level_enum_descriptors_TwistWithCovariance_2eproto,
    file_level_service_descriptors_TwistWithCovariance_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_TwistWithCovariance_2eproto_getter() {
  return &descriptor_table_TwistWithCovariance_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_TwistWithCovariance_2eproto(&descriptor_table_TwistWithCovariance_2eproto);
namespace LSLAM {

// ===================================================================

class TwistWithCovariance::_Internal {
 public:
  static const ::LSLAM::Twist& twist(const TwistWithCovariance* msg);
};

const ::LSLAM::Twist&
TwistWithCovariance::_Internal::twist(const TwistWithCovariance* msg) {
  return *msg->_impl_.twist_;
}
void TwistWithCovariance::clear_twist() {
  if (GetArenaForAllocation() == nullptr && _impl_.twist_ != nullptr) {
    delete _impl_.twist_;
  }
  _impl_.twist_ = nullptr;
}
TwistWithCovariance::TwistWithCovariance(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:LSLAM.TwistWithCovariance)
}
TwistWithCovariance::TwistWithCovariance(const TwistWithCovariance& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TwistWithCovariance* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.covariance_){from._impl_.covariance_}
    , decltype(_impl_.twist_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_twist()) {
    _this->_impl_.twist_ = new ::LSLAM::Twist(*from._impl_.twist_);
  }
  // @@protoc_insertion_point(copy_constructor:LSLAM.TwistWithCovariance)
}

inline void TwistWithCovariance::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.covariance_){arena}
    , decltype(_impl_.twist_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TwistWithCovariance::~TwistWithCovariance() {
  // @@protoc_insertion_point(destructor:LSLAM.TwistWithCovariance)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TwistWithCovariance::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.covariance_.~RepeatedField();
  if (this != internal_default_instance()) delete _impl_.twist_;
}

void TwistWithCovariance::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TwistWithCovariance::Clear() {
// @@protoc_insertion_point(message_clear_start:LSLAM.TwistWithCovariance)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.covariance_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.twist_ != nullptr) {
    delete _impl_.twist_;
  }
  _impl_.twist_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TwistWithCovariance::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .LSLAM.Twist twist = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_twist(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated double covariance = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_covariance(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 17) {
          _internal_add_covariance(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TwistWithCovariance::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LSLAM.TwistWithCovariance)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .LSLAM.Twist twist = 1;
  if (this->_internal_has_twist()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::twist(this),
        _Internal::twist(this).GetCachedSize(), target, stream);
  }

  // repeated double covariance = 2;
  if (this->_internal_covariance_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_covariance(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LSLAM.TwistWithCovariance)
  return target;
}

size_t TwistWithCovariance::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LSLAM.TwistWithCovariance)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double covariance = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_covariance_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // .LSLAM.Twist twist = 1;
  if (this->_internal_has_twist()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.twist_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TwistWithCovariance::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TwistWithCovariance::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TwistWithCovariance::GetClassData() const { return &_class_data_; }


void TwistWithCovariance::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TwistWithCovariance*>(&to_msg);
  auto& from = static_cast<const TwistWithCovariance&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LSLAM.TwistWithCovariance)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.covariance_.MergeFrom(from._impl_.covariance_);
  if (from._internal_has_twist()) {
    _this->_internal_mutable_twist()->::LSLAM::Twist::MergeFrom(
        from._internal_twist());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TwistWithCovariance::CopyFrom(const TwistWithCovariance& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LSLAM.TwistWithCovariance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TwistWithCovariance::IsInitialized() const {
  return true;
}

void TwistWithCovariance::InternalSwap(TwistWithCovariance* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.covariance_.InternalSwap(&other->_impl_.covariance_);
  swap(_impl_.twist_, other->_impl_.twist_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TwistWithCovariance::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TwistWithCovariance_2eproto_getter, &descriptor_table_TwistWithCovariance_2eproto_once,
      file_level_metadata_TwistWithCovariance_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace LSLAM
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::LSLAM::TwistWithCovariance*
Arena::CreateMaybeMessage< ::LSLAM::TwistWithCovariance >(Arena* arena) {
  return Arena::CreateMessageInternal< ::LSLAM::TwistWithCovariance >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
