// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WifiLamp.proto

#include "WifiLamp.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace LSLAM {
PROTOBUF_CONSTEXPR WifiLamp::WifiLamp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.wifi_connecting_)*/false
  , /*decltype(_impl_.wifi_connection_successful_)*/false
  , /*decltype(_impl_.start_distribution_network_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WifiLampDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WifiLampDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WifiLampDefaultTypeInternal() {}
  union {
    WifiLamp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WifiLampDefaultTypeInternal _WifiLamp_default_instance_;
}  // namespace LSLAM
static ::_pb::Metadata file_level_metadata_WifiLamp_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_WifiLamp_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_WifiLamp_2eproto = nullptr;

const uint32_t TableStruct_WifiLamp_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::LSLAM::WifiLamp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _split_
  ~0u,  // no sizeof(Split)
  PROTOBUF_FIELD_OFFSET(::LSLAM::WifiLamp, _impl_.wifi_connecting_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::WifiLamp, _impl_.wifi_connection_successful_),
  PROTOBUF_FIELD_OFFSET(::LSLAM::WifiLamp, _impl_.start_distribution_network_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::LSLAM::WifiLamp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::LSLAM::_WifiLamp_default_instance_._instance,
};

const char descriptor_table_protodef_WifiLamp_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016WifiLamp.proto\022\005LSLAM\"k\n\010WifiLamp\022\027\n\017w"
  "ifi_connecting\030\001 \001(\010\022\"\n\032wifi_connection_"
  "successful\030\002 \001(\010\022\"\n\032start_distribution_n"
  "etwork\030\003 \001(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_WifiLamp_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_WifiLamp_2eproto = {
    false, false, 140, descriptor_table_protodef_WifiLamp_2eproto,
    "WifiLamp.proto",
    &descriptor_table_WifiLamp_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_WifiLamp_2eproto::offsets,
    file_level_metadata_WifiLamp_2eproto, file_level_enum_descriptors_WifiLamp_2eproto,
    file_level_service_descriptors_WifiLamp_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_WifiLamp_2eproto_getter() {
  return &descriptor_table_WifiLamp_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_WifiLamp_2eproto(&descriptor_table_WifiLamp_2eproto);
namespace LSLAM {

// ===================================================================

class WifiLamp::_Internal {
 public:
};

WifiLamp::WifiLamp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:LSLAM.WifiLamp)
}
WifiLamp::WifiLamp(const WifiLamp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WifiLamp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.wifi_connecting_){}
    , decltype(_impl_.wifi_connection_successful_){}
    , decltype(_impl_.start_distribution_network_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.wifi_connecting_, &from._impl_.wifi_connecting_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.start_distribution_network_) -
    reinterpret_cast<char*>(&_impl_.wifi_connecting_)) + sizeof(_impl_.start_distribution_network_));
  // @@protoc_insertion_point(copy_constructor:LSLAM.WifiLamp)
}

inline void WifiLamp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.wifi_connecting_){false}
    , decltype(_impl_.wifi_connection_successful_){false}
    , decltype(_impl_.start_distribution_network_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

WifiLamp::~WifiLamp() {
  // @@protoc_insertion_point(destructor:LSLAM.WifiLamp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WifiLamp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void WifiLamp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WifiLamp::Clear() {
// @@protoc_insertion_point(message_clear_start:LSLAM.WifiLamp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.wifi_connecting_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.start_distribution_network_) -
      reinterpret_cast<char*>(&_impl_.wifi_connecting_)) + sizeof(_impl_.start_distribution_network_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WifiLamp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool wifi_connecting = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.wifi_connecting_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool wifi_connection_successful = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.wifi_connection_successful_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool start_distribution_network = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.start_distribution_network_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WifiLamp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LSLAM.WifiLamp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool wifi_connecting = 1;
  if (this->_internal_wifi_connecting() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_wifi_connecting(), target);
  }

  // bool wifi_connection_successful = 2;
  if (this->_internal_wifi_connection_successful() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_wifi_connection_successful(), target);
  }

  // bool start_distribution_network = 3;
  if (this->_internal_start_distribution_network() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_start_distribution_network(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LSLAM.WifiLamp)
  return target;
}

size_t WifiLamp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LSLAM.WifiLamp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool wifi_connecting = 1;
  if (this->_internal_wifi_connecting() != 0) {
    total_size += 1 + 1;
  }

  // bool wifi_connection_successful = 2;
  if (this->_internal_wifi_connection_successful() != 0) {
    total_size += 1 + 1;
  }

  // bool start_distribution_network = 3;
  if (this->_internal_start_distribution_network() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WifiLamp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WifiLamp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WifiLamp::GetClassData() const { return &_class_data_; }


void WifiLamp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WifiLamp*>(&to_msg);
  auto& from = static_cast<const WifiLamp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LSLAM.WifiLamp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_wifi_connecting() != 0) {
    _this->_internal_set_wifi_connecting(from._internal_wifi_connecting());
  }
  if (from._internal_wifi_connection_successful() != 0) {
    _this->_internal_set_wifi_connection_successful(from._internal_wifi_connection_successful());
  }
  if (from._internal_start_distribution_network() != 0) {
    _this->_internal_set_start_distribution_network(from._internal_start_distribution_network());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WifiLamp::CopyFrom(const WifiLamp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LSLAM.WifiLamp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WifiLamp::IsInitialized() const {
  return true;
}

void WifiLamp::InternalSwap(WifiLamp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WifiLamp, _impl_.start_distribution_network_)
      + sizeof(WifiLamp::_impl_.start_distribution_network_)
      - PROTOBUF_FIELD_OFFSET(WifiLamp, _impl_.wifi_connecting_)>(
          reinterpret_cast<char*>(&_impl_.wifi_connecting_),
          reinterpret_cast<char*>(&other->_impl_.wifi_connecting_));
}

::PROTOBUF_NAMESPACE_ID::Metadata WifiLamp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_WifiLamp_2eproto_getter, &descriptor_table_WifiLamp_2eproto_once,
      file_level_metadata_WifiLamp_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace LSLAM
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::LSLAM::WifiLamp*
Arena::CreateMaybeMessage< ::LSLAM::WifiLamp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::LSLAM::WifiLamp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
